import requests
import json

countries_default = [
    [0,"Austria"],
    [0,"Belgium"],
    [0,"Bulgaria"],
    [0,"Switzerland"],
    [0,"Cyprus"],
    [0,"Czechia"],
    [0,"Germany"],
    [0,"Denmark"],
    [0,"Spain"],
    [0,"Estonia"],
    [0,"Finland"],
    [0,"France"],
    [0,"Greece"],
    [0,"Croatia"],
    [0,"Hungary"],
    [0,"Ireland"],
    [0,"Italy"],
    [0,"Iceland"],
    [0,"Lithuania"],
    [0,"Luxembourg"],
    [0,"Latvia"],
    [0,"Malta"],
    [0,"Netherlands"],
    [0,"Norway"],
    [0,"Poland"],
    [0,"Portugal"],
    [0,"Romania"],
    [0,"Slovakia"],
    [0,"Slovenia"],
    [0,"Sweden"]  
]

countries_corporate_tax_2023 = [
    [23,"Austria"],
    [25,"Belgium"],
    [10,"Bulgaria"],
    [14.6,"Switzerland"],
    [12.5,"Cyprus"],
    [21,"Czechia"],
    [30,"Germany"],
    [22,"Denmark"],
    [25,"Spain"],
    [20,"Estonia"],
    [20,"Finland"],
    [25,"France"],
    [22,"Greece"],
    [18,"Croatia"],
    [9,"Hungary"],
    [12.5,"Ireland"],
    [24,"Italy"],
    [21,"Iceland"],
    [15,"Lithuania"],
    [24.94,"Luxembourg"],
    [20,"Latvia"],
    [35,"Malta"],
    [25.8,"Netherlands"],
    [22,"Norway"],
    [19,"Poland"],
    [21,"Portugal"],
    [16,"Romania"],
    [21,"Slovakia"],
    [22,"Slovenia"],
    [20.6,"Sweden"]  
]

countries_capital_gains_tax_2023 = [
    [27.5,"Austria"],
    [0,"Belgium"],
    [10,"Bulgaria"],
    [0,"Switzerland"],
    [20,"Cyprus"],
    [0,"Czechia"],
    [26.4,"Germany"],
    [42,"Denmark"],
    [28,"Spain"],
    [20,"Estonia"],
    [34,"Finland"],
    [34,"France"],
    [15,"Greece"],
    [12,"Croatia"],
    [15,"Hungary"],
    [33,"Ireland"],
    [26,"Italy"],
    [22,"Iceland"],
    [20,"Lithuania"],
    [0,"Luxembourg"],
    [20,"Latvia"],
    [0,"Malta"],
    [33,"Netherlands"],
    [37.8,"Norway"],
    [19,"Poland"],
    [28,"Portugal"],
    [10,"Romania"],
    [0,"Slovakia"],
    [0,"Slovenia"],
    [30,"Sweden"]  
]

countries_home_affordability = [
    [11.2,"Austria"],
    [6.8,"Belgium"],
    [9.5,"Bulgaria"],
    [10.3,"Switzerland"],
    [8.2,"Cyprus"],
    [12.8,"Czechia"],
    [9.3,"Germany"],
    [6.2,"Denmark"],
    [8.1,"Spain"],
    [11.1,"Estonia"],
    [8.5,"Finland"],
    [11.3,"France"],
    [13.2,"Greece"],
    [12.9,"Croatia"],
    [13.7,"Hungary"],
    [7.25,"Ireland"],
    [10.3,"Italy"],
    [6,"Iceland"],
    [12,"Lithuania"],
    [9.1,"Luxembourg"],
    [9,"Latvia"],
    [12.1,"Malta"],
    [7.8,"Netherlands"],
    [7.8,"Norway"],
    [11.8,"Poland"],
    [13.2,"Portugal"],
    [10.5,"Romania"],
    [14.6,"Slovakia"],
    [12.5,"Slovenia"],
    [7.8,"Sweden"]  
]

countries_value_added_tax = [
    [20,"Austria"],
    [21,"Belgium"],
    [20,"Bulgaria"],
    [8.1,"Switzerland"],
    [19,"Cyprus"],
    [21,"Czechia"],
    [19,"Germany"],
    [25,"Denmark"],
    [21,"Spain"],
    [22,"Estonia"],
    [24,"Finland"],
    [20,"France"],
    [24,"Greece"],
    [25,"Croatia"],
    [27,"Hungary"],
    [23,"Ireland"],
    [22,"Italy"],
    [24,"Iceland"],
    [21,"Lithuania"],
    [17,"Luxembourg"],
    [21,"Latvia"],
    [18,"Malta"],
    [21,"Netherlands"],
    [25,"Norway"],
    [23,"Poland"],
    [23,"Portugal"],
    [19,"Romania"],
    [23,"Slovakia"],
    [22,"Slovenia"],
    [25,"Sweden"]  
]


#Write data
from update_country_data import write_data

data_to_write = countries_value_added_tax
indicator = "Value added tax"
year = "2023"

for country in data_to_write:
    write_data(year, indicator, {country[1]: country[0]})


